// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBgmv1ZmweO-s0EY2CxIAfYj-vQ-KNb8',
    appId: '1:47233059473:web:b7fe9a0046ebebc6c0cd30',
    messagingSenderId: '47233059473',
    projectId: 'malnutrition-app-9e174',
    authDomain: 'malnutrition-app-9e174.firebaseapp.com',
    storageBucket: 'malnutrition-app-9e174.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_SEizk5-rqC74L1yxLTIKD2JDllg8Mvk',
    appId: '1:47233059473:android:a95192bd32a4d811c0cd30',
    messagingSenderId: '47233059473',
    projectId: 'malnutrition-app-9e174',
    storageBucket: 'malnutrition-app-9e174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7J-IPLpMK_xH-5bzB-XfcWIXq2476ANo',
    appId: '1:47233059473:ios:b317f7a01872a264c0cd30',
    messagingSenderId: '47233059473',
    projectId: 'malnutrition-app-9e174',
    storageBucket: 'malnutrition-app-9e174.firebasestorage.app',
    iosBundleId: 'com.example.malnutritionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7J-IPLpMK_xH-5bzB-XfcWIXq2476ANo',
    appId: '1:47233059473:ios:b317f7a01872a264c0cd30',
    messagingSenderId: '47233059473',
    projectId: 'malnutrition-app-9e174',
    storageBucket: 'malnutrition-app-9e174.firebasestorage.app',
    iosBundleId: 'com.example.malnutritionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaBgmv1ZmweO-s0EY2CxIAfYj-vQ-KNb8',
    appId: '1:47233059473:web:7442f7a1a3391435c0cd30',
    messagingSenderId: '47233059473',
    projectId: 'malnutrition-app-9e174',
    authDomain: 'malnutrition-app-9e174.firebaseapp.com',
    storageBucket: 'malnutrition-app-9e174.firebasestorage.app',
  );
}
